version: "3"
services:
  postgres:
    image: "postgres:10.9-alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/main/resources/db/scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
